# Generated by Django 4.1.1 on 2022-09-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField()),
                ("status", models.BooleanField(default=True)),
            ],
        ),
    ]
