# Generated by Django 4.1.1 on 2022-09-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtaapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="updated_at", field=models.DateTimeField(null=True),
        ),
    ]
