# Generated by Django 4.1.1 on 2022-09-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtaapi", "0002_alter_user_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(name="user", options={"ordering": ("name",)},),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
