# Generated by Django 4.1.1 on 2022-09-22 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("gtaapi", "0003_alter_user_options_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("83c39c3e-638f-439c-b7cc-a0db417da5d0"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
